client_name: # name can be anything
#    container_name: federation-lab-client2 # what the name for this container would be
    restart: "no" # if it crashes for example
    build: . # look for the docker file where this file is currently located
    volumes:
      - ./docker_data:/opt/federation-lab/data
      - ./default_models:/opt/federation-lab/default_models
      - ./data_loaders:/opt/federation-lab/data_loaders
    environment:
      - PYTHONUNBUFFERED=1
      - RANK={rank}
      - WORLD_SIZE={world_size}
    ports:
      - "5002:5000" # {machine-port}:{docker-port}
    depends_on:
      - "fl_server"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M
