---
# Experiment configuration
total_epochs: 5
epochs_per_cycle: 1
wait_for_clients: true
net: Cifar10CNN
dataset: cifar10
# Use cuda is available; setting to false will force CPU
cuda: true
experiment_prefix: 'experiment_single_machine'
output_location: 'output'
tensor_board_active: true
clients_per_round: 1
system:
  federator:
    hostname: '131.180.40.72'
    nic: 'ens4'
  clients:
    amount: 1
